# Generated by Django 3.1.4 on 2023-11-11 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userbase',
            old_name='address_line_1',
            new_name='address_1',
        ),
        migrations.RenameField(
            model_name='userbase',
            old_name='address_line_2',
            new_name='address_2',
        ),
        migrations.RenameField(
            model_name='userbase',
            old_name='town_city',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='userbase',
            old_name='phone_number',
            new_name='phone',
        ),
        migrations.RenameField(
            model_name='userbase',
            old_name='postcode',
            new_name='zipcode',
        ),
        migrations.AddField(
            model_name='userbase',
            name='last_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='userbase',
            name='first_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='userbase',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
