# Generated by Django 3.1.4 on 2023-11-11 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20231111_0918'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbase',
            name='state',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
